# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'p1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
import sys
import string

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1228, 1039)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-10, -10, 1241, 1031))
        self.widget.setStyleSheet("#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0.12, y1:0.221636, x2:0.930801, y2:0.58, stop:0 rgba(0, 79, 239, 255), stop:0.970149 rgba(255, 255, 255, 255))\n"
"}")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(520, 530, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:rgb(153, 211, 255);\n"
"border:2px solid white;\n"
                                       "QPushButton::hover"
                             "{"
                             "background-color : lightgreen;"
                             "}"
  
"")
        self.pushButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(370, 360, 521, 61))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(320, 120, 641, 211))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(36)
        self.label.setFont(font)
        self.lineEdit.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1228, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # creating a QGraphicsDropShadowEffect object
        shadow = QGraphicsDropShadowEffect()
        shadow1 = QGraphicsDropShadowEffect()

        # setting blur radius
        shadow.setBlurRadius(15)
        shadow1.setBlurRadius(15)

        # adding shadow to the label
        self.lineEdit.setGraphicsEffect(shadow)
        self.pushButton.setGraphicsEffect(shadow1)
    #click event
        self.pushButton.clicked.connect(self.generate)
    #gerenate function
    def generate(self):
        a=string.ascii_letters
        b=string.digits
        c=string.punctuation
        password=""
        import random
        for i in range(4):
            password+=random.choice(b)
        password+=random.choice(a)
        password+=random.choice(a)
        password+=random.choice(c)
        self.lineEdit.setText(password)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>hh</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Pass GEn"))
        self.label.setText(_translate("MainWindow", "Password GEnerator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
